#carga librerias 
library(shiny)
library(shinydashboard)
library(shinyWidgets)
library(ggplot2)
library(plotly)
library(DT)
library(dplyr)
library(maps)
library(highcharter)
library(readxl)
library(stringr)
library(tidyverse)
library(purrr)
library(forecast)
library(stats)
library(kableExtra)

source('script/data_treatment.R')
